### ISSUE TITLE
Which C++ library?

### ISSUE THREAD

**Issue by pb-cdunn** [SciNim/flambeau#2]
Hi. This is a good start. I have a request: Could you name precisely which C++ library you're wrapping? Maybe in a readme?

**Comment by mratsim** [comment]
The library is libTorch: doc is here: https://pytorch.org/cppdocs/

**Comment by pb-cdunn** [comment]
https://pytorch.org/cppdocs/installing.html

Aha. I see now. It's a C++ (w/ cmake) project embedded within the repo for the Python project. Thank you. You've got so much really great stuff.
