### ISSUE TITLE
define NOMINMAX when compiling your program on Windows

### ISSUE THREAD

**Issue by HugoGranstrom** [SciNim/flambeau#28]
When trying to run the `nn` test I got this error on Windows:
```
C:\Users\hugog\code\nim\flambeau\vendor\libtorch\include\c10/util/C++17.h(28): fatal error C1189: #error:  Macro clash with min and max -- define NOMINMAX when compiling your program on Windows
```
It was solved by passing this with the compiler:
``-t:-DNOMINMAX``
Not sure where and how to define it so that it is applied to all files in Flambeau. :/

**Comment by Clonkk** [comment]
You need to import a file that re-export that contains ``{.passC:"-DNOMINMAX.}``. We could reuse config.nim for this purpose.

**Comment by HugoGranstrom** [comment]
Oh right, that's true 😄

**Comment by HugoGranstrom** [comment]
Doing it in config.nim sounds sounds most straightforward 👍
We will probably have to add more flags in the future if we stumble upon more of these.

**Comment by Clonkk** [comment]
That's how I did it in nimjl : https://github.com/Clonkk/nimjl/blob/master/nimjl/config.nim

**Comment by HugoGranstrom** [comment]
Nice, it works like a charm now :)
