### ISSUE TITLE
`hasCuda` is not in global Torch scope

### ISSUE THREAD

**Issue by Vindaar** [SciNim/flambeau#30]
The `hasCuda` procedure, which should return whether the linked Torch library was compiled with CUDA support, does not live in the global Torch namespace.

In the Torch documentation that procedure isn't even found, but checking locally in the header files, the ATen library contains it in the `Context.h`.

**Comment by Clonkk** [comment]
Do you mean ``hasCuda`` shouldn't be binded to ``torch::hasCuda`` or that the Nim symbol isn't exported by default ?

**Comment by Vindaar** [comment]
I'm saying that the current implementation of `hasCuda` doesn't work (which does indeed try to bind it to `torch::hasCuda`) and I couldn't figure out how to fix it locally. Opened the issue to not forget about it.

**Comment by Clonkk** [comment]
is_cuda_abailable is now exported, this should fix this ticker
