### ISSUE TITLE
nimble file with torch_installer run on install

### ISSUE THREAD

**Issue by mratsim** [SciNim/flambeau#6]
We want a nimble file that build and run the torch installer so that the required library are downloaded.

We can use a before install task for that similar to nimgen/nimterop libraries:
See https://github.com/genotrance/nim7z/blob/cc6c2b0/nim7z.nimble#L20-L27

**Comment by Clonkk** [comment]
I think we close this with https://github.com/SciNim/flambeau/pull/12 (to be tested on a clean install when I have time)

**Comment by Clonkk** [comment]
Local nimble install / nimble develop now properly downloads the lib. Closing this
